### ISSUE TITLE
Fusion base directory is not mounted

### ISSUE THREAD

**Issue by czzmmc** [apache/incubator-teaclave#287]
I see u guys made a lot of changes. And I cloned ur the newest code to give it a shot. I have to say this is much better than the old version. But when I was try to launch Teaclave Services with docker-compose command, I got a situation here. Like below.

teaclave-execution-service         | [2020-05-07T04:25:14Z ERROR teaclave_execution_service_enclave] Failed to start the service: Fusion base directory is not mounted: /tmp/fusion_data
teaclave-execution-service         | Service exit with error: ServiceError
teaclave-execution-service exited with code 0

It seems the execution-service is down because of a mount thing. Waiting for any help. BTW, if I run it successfully, what would I see when I hit the link(https://api.trustedservices.intel.com:443). I don not see any doc about it. BTW AGAIN, the new docs ur uploaded explain my lots of questions.

**Comment by mssun** [comment]
"Fusion base directory" is a directory for store temporary (encrypted) fusion data and can be set in the runtime config (https://github.com/apache/incubator-teaclave/blob/master/config/runtime.config.toml#L34).

The issue is caused by a check in the execution service (https://github.com/apache/incubator-teaclave/blob/master/services/execution/enclave/src/lib.rs#L66). You can create a directory by your self in `/tmp/fusion_data` to start the service.

Thanks for your report. We will propose a better implementation for this case.

At last, the link you mentioned (https://api.trustedservices.intel.com:443) is the URL of attestation service. API  specifications can be found here: https://software.intel.com/content/dam/develop/public/us/en/documents/sgx-attestation-api-spec.pdf.
