### ISSUE TITLE
builtin_echo failed with large input

### ISSUE THREAD

**Issue by yc-huang** [apache/incubator-teaclave#392]
The python client will fail with large input arguments; this could be replicated by running builtin_echo example with large input (e.g. the project LICENSE file, size 11887).

-  increase the heap size of both storage and management service (service/[storage, management]/enclave/Enclave.config.xml) to e.g. 0x4000000 could avoid the oom issue;
-  it seems that the rpc reqs/resps could be too verbose / low efficiency;
-  it seems that the response payload get truncated somewhere to 16k(16384) and become malformed.

**Comment by mssun** [comment]
I have increased the default to 256M in this commit #396 and fixed the truncated response issue in the Python client SDK.

For the large input, we don't suggest to send as function parameters and we may consider to limit the size of an RPC message later. One reason is that the current RPC is in JSON format which does not support raw binary data very well. That's why large inputs consume many memory when parsing the RPC messages. This situation will be improved if we support HTTP(s).

**Comment by yc-huang** [comment]
Thanks @mssun,  my local test confirmed that this had been fixed.
