### ISSUE TITLE
Cargo build error for Rust SDK

### ISSUE THREAD

**Issue by Mengyuan-L** [apache/incubator-teaclave#465]
Hi all,
 
When I tried to cargo build `/teaclave/sdk/rust/`, I met the following error:

```
error: failed to run custom build command for `teaclave_proto v0.1.0 (/teaclave/services/proto)`
Caused by:
  process didn't exit successfully: `/teaclave/sdk/rust/target/debug/build/teaclave_proto-1f6374e59418fb11/build-script-build` (exit code: 101)

--- stderr
thread 'main' panicked at 'stdout: "error: failed to download `ansi_term v0.11.0`\n\nCaused by:\n  can\'t make HTTP request in the offline mode\n", stderr: "error: failed to download `ansi_term v0.11.0`\n\nCaused by:\n  can\'t make HTTP request in the offline mode\n"', /teaclave/services/proto/build.rs:76:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Mengyuan-L** [comment]
The problem can be solved by commenting cargo build option "--offline"  in /services/proto/build.rs. I guess there are some new packets needed by building the sdk. Maybe a update is needed here. 
Thanks

**Comment by mssun** [comment]
Thanks for reporting this. No, this is not caused by the needs of new crates.

This is because all of our dependencies for the frameworks, SDKs, cli, etc. are vendored for offline building. However, this is managed by the build system (i.e., cmake). If you want to compile a crate directly in side the directory, there may be some compilation errors.

In your case, I'm thinking about the solution. Maybe, putting a `Cargo.lock` should work.
