### ISSUE TITLE
SEV 支持

### ISSUE THREAD

**Issue by zwying** [apache/incubator-teaclave#490]
(Write your question here.)

![image](https://user-images.githubusercontent.com/58444/109464157-2b513e00-7aa1-11eb-8384-50ce1809e4fb.png)
 You mentioned SEV support in the above picture, so I am wondering what's the status of AMD platform support to run MesaTee. thanks!

**Comment by mssun** [comment]
Since AMD SEV isn't mature enough to support our current platform, we don't have plan to integrate it in this year. However, we'll keep eye on it and will release a short report of the feasibility of AMD SEV in the near future.

If you're interested in our 2021 plan, please read this blog (https://teaclave.apache.org/blog/2021-01-19-roadmap-in-2021-project-maturity-and-community-buildup/) and also documented in the issue #460 . Thanks.

**Comment by mssun** [comment]
Also, please read all documents around Teaclave instead. Others may cause some confusion. Thanks.

**Comment by zwying** [comment]
thanks for the quick answer.

**Comment by mssun** [comment]
You're welcome.
