### ISSUE TITLE
Have an example or rewrite some examples with MesaTEE CLI

### ISSUE THREAD

**Issue by mssun** [apache/incubator-teaclave#59]
We need to rewrite or have a some examples to demonstrate the usage of CLI. Actually, there is no need to use the MesaTEE SDK if the example is very simple.

For example, we can rewrite the `py_file` example using shell script with the CLI instead of writing a rust program like this (https://github.com/apache/incubator-mesatee/blob/master/examples/py_file/src/main.rs).

**Comment by hi-T0day** [comment]
Hi, I have done this good first issue in my branch. [Commit here!](https://github.com/hi-T0day/incubator-teaclave/commit/7fbc56aa61c04268b9a6525ba8e756a214473fe1)

I use a  Python script to combine upload file, create task and invoke task. Meanwhile, encrypt command parameter is added to the CLI in order to encrypt file locally. 

This python script and teaclave-cli work well in the master branch. 

Besides, the version of structopt crates is 0.2.8 in both master and develop branch, I suggest to update to the latest version 0.3.9 which can provide more options.

**Comment by mssun** [comment]
Thanks for your implementation. Currently, we are working on the `develop` branch, and current `master` branch will be deprecated. Anyway, although we haven't started to develop the CLI, your implementation is definitely useful for our new version.

BTW, I have updated the `structopt` to 0.3.9 in https://github.com/apache/incubator-teaclave/commit/9915d901d89fd361a244f6784629fc948b2e725a.

Thanks!

**Comment by mssun** [comment]
We are working on examples based on the new API design. Therefore, this issue is no longer valid. Closed.
