### ISSUE TITLE
ERROR mesatee_core::rpc::sgx::ra RACACHE renewal failed

### ISSUE THREAD

**Issue by z1queue** [apache/incubator-teaclave#61]
I have 2 computers, When i run mesatee service in Ubuntu 18.04， Occasionally, such a mistake occur:

![RACACHE renewal failed](https://user-images.githubusercontent.com/53327024/68946922-19d21d00-07ef-11ea-91f8-ba385d09f197.png)

> ERROR mesatee_core::rpc::sgx::ra RACACHE renewal failed
thread panicked at 'explicit panic', mesatee_core/src/rpc/sgx/ra.rs:548:9
statck backtrace:
.....
.....
.....
fatal runtime error: failed to initiate panic, error 5
Illegal instructioin (core dumped)

I try to restart the computer, pull the code and make the project again，it‘s still not work.
I ues Shadowsocks to config the network proxy, it works.

so, i think this error is related to the network environment, such as DNS cache or other problem.
I try this command in the other computer 

> sudo /etc/init.d/dns-clean start

it works!

Maybe we can add this command to the service.sh

**Comment by z1queue** [comment]
![RACACHE renewal failed](https://user-images.githubusercontent.com/53327024/68946771-bcd66700-07ee-11ea-90cb-dc763092b807.jpg)

**Comment by z1queue** [comment]
![RACACHE renewal failed](https://user-images.githubusercontent.com/53327024/68946890-02932f80-07ef-11ea-8225-c0aee5385b1e.png)

**Comment by mssun** [comment]
Hi @z1queue, thanks for the report.

First of all, the "RACACHE renewal failed" error is an expected panic. This error is caused by some issues with IAS connection. Since the main **trust** of MesaTEE is **established and ensured** by a successful RA, MesaTEE should not work if there are any issues related with RA.

With above statement, for your case, we definitely need to do some improvements:

  - a better error message (and panic message): users can understand the causes of the panic
  - mechanism to retry RA: make MesaTEE more robust under a poor network environment

I'll create an issue to track these two improvements.

**Comment by mssun** [comment]
Just come up another solution:
  - propagate error to RPC caller and make sure services handle the failure.
